### ISSUE TITLE
[404] Error connecting to the API (https://api.coinsecure.in//v1/exchange/max24Hr)

### ISSUE THREAD

**Issue by webcluesrepo** [coinsecure/plugins#1]
I have 
[404] Error connecting to the API (https://api.coinsecure.in//v1/exchange/max24Hr)
Error When Calling API

**Comment by vivek0** [comment]
Remove extra '/'   use https://api.coinsecure.in/v1/exchange/max24Hr

**Comment by vivek0** [comment]
Fixed a419da42e6a8d007a09055b7140a002c45c3be32
